name: build

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron:  '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install npm dependencies
      run: yarn install

    - name: Run linters
      run: yarn lint

    - name: Build
      run: yarn build

    - name: Setup ruby
      uses: actions/setup-ruby@v1

    - name: Run awesome_bot
      run: |
        gem install awesome_bot
        awesome_bot index.html --allow-dupe --allow-redirect --skip-save-results --white-list "https://codepen.io/pen/define"
